# Generated by Django 4.2.5 on 2023-10-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amountAdd', models.IntegerField()),
                ('nameAdd', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amountSub', models.IntegerField()),
                ('nameSub', models.CharField(max_length=225, unique=True)),
            ],
        ),
    ]
